print("My name is Nada Mowafi")
print("my age is 21 ")
print("My department is communication ad electronics")
print("I will bw graduated in 2025")
print("My favorite team is software")
print("I live in egypt")