print("My name is Nada Mowafi")
print("my age is 21 ")
print("My department is communication ad electronics")
print("I will bw graduated in 2025")
print("My favorite team is software")
print("I live in egypt")
print("my fav color is pink")
print("i have 3 brothers")
print("my fav food is pasta")
print("i was born at 23 sep 2002")
print("i live in agamy")
print("my mail is nadat380@gmail.com")